exceptions_arr = {
    'ValueError': 'Введены данные некорректного типа',
    'WrongLimitsArgument': 'Введенные данные не соответсвуют ни одному пункту',
    'FileNotFound': 'Файл с таким именем не найден',
    'TooMuchArguments': 'Передано слишком много аргументов',
    'TooLittleArguments': 'Передано слишком мало аргументов',
}